CMS:
  SECRET_KEY: 'real_secret_here'
  DB_NAME: cms_db

  SITENAME: Flask CMS
  TITLE: Hello
  DESCRIPTION: Awesome Blog
  ABOUT: This is my blog, I am xyz
  LINKS:
    - ['Github', 'http://github.com']
    - ['Twitter', 'http://twitter.com']


  # https://bootswatch.com/
  SWATCH: united

  HOST: '0.0.0.0'
  PORT: 5000
  DEBUG: false
  RELOADER: true
  
  EXTENSIONS:
    - cms.ext.database.configure
    - cms.ext.admin.configure
    - cms.ext.auth.configure
    - cms.ext.debug.configure
    - cms.ext.blog.configure
    - flask_bootstrap.Bootstrap
    - cms.ext.markdown.configure

  DEBUG_TOOLBAR_ENABLED: true
  DEBUG_TB_INTERCEPT_REDIRECTS: false
  DEBUG_TB_PROFILER_ENABLED: true
  DEBUG_TB_TEMPLATE_EDITOR_ENABLED: true

  SIMPLE_LOGIN_HOME_URL: /admin

  FLASK_ADMIN_NAME: Flask CMS!
  FLASK_ADMIN_TEMPLATE_MODE: bootstrap3
  FLASK_ADMIN_SWATCH: default
